language: node_js
dist: trusty
node_js:
  - "9"
install:
  - yarn
  - npm install -g hexo

script:
  - npm run init
  - npm run build
  - cd public

cache:
  directories:
    - node_modules

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN