language: node_js
dist: trusty
node_js:
  - "9"
install:
  - yarn
  - npm install -g hexo

script:
  - npm run init
  - npm run build
  - echo "blog.indexyz.me" > public/CNAME

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: indexyz@protonmail.com
  local-dir: public
  name: Travis Automatically Bot
  on:
    branch: master
