language: node_js
dist: trusty
node_js:
  - "9"
install:
  - yarn
  - npm install -g hexo

script:
  - npm run init
  - npm run build


cache:
  directories:
    - node_modules

after_success:
  - cd public
  - git init
  - git add -A
  - git commit -m "Delopy commit by Travis CI"
  - git remote add deploy $DEPLOY_REPO_URL
  - git push deploy master -f
